import { Player, MatchFixture, ClubAward } from './types';

export const CLUB_INFO = {
  name: 'Blessed KAA Football Academy',
  shortName: 'BKFA',
  nickname: 'The Conquerors',
  founded: '2014',
  location: 'Jos, Plateau State, Nigeria',
  stadium: 'Science Day Arena / Rwang Pam Stadium, Jos',
  capacity: '15,000',
  instagram: 'https://www.instagram.com/blessedkaafa/',
  instagramHandle: '@blessedkaafa',
  phone: '+234 803 123 4567',
  email: 'info@blessedkaafa.com',
  motto: 'The Light That Can Not Be Hidden',
  subMotto: 'The Conquerors • Since 2014',
  description: 'Blessed KAA Football Academy (BKFA) — "The Conquerors" — is a premier grassroots football academy in Jos, Plateau State, founded in 2014 to develop and launch top-tier male and female football talents to national and global stardom.',
};

export const PLAYERS_DATA: Player[] = [
  // ===================== MEN'S FIRST TEAM =====================
  {
    id: 'emmanuel-danjuma',
    name: 'Emmanuel Danjuma',
    nickname: 'The Plateau Maestro',
    jerseyNumber: 10,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Midfielder',
    detailedPosition: 'Attacking Playmaker',
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    captain: true,
    age: 21,
    dateOfBirth: '2005-04-12',
    height: "5' 10\" (178 cm)",
    weight: '71 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2021,
    marketValueEstimate: '€180,000',
    bio: 'Captain and talisman of the BKFA Men’s team. Emmanuel possesses extraordinary vision, pinpoint passing range, and a lethal right foot from set-pieces. He came through the BKFA grassroots ranks and led the academy to the 2024 Plateau State Grassroots Championship triumph.',
    scoutReport: 'Elite spatial awareness, agile under heavy pressure, exceptional chance creation metric (2.8 key passes/90), captain mentality with outstanding leadership.',
    achievements: [
      'BKFA Player of the Season 2024',
      'Plateau Grassroots League MVP 2024',
      'Top Assist Provider (14 assists in 2024)',
    ],
    attributes: {
      pace: 84,
      shooting: 82,
      passing: 91,
      dribbling: 88,
      defending: 58,
      physical: 76,
    },
    seasonStats: {
      appearances: 22,
      goals: 9,
      assists: 14,
      minutesPlayed: 1940,
      yellowCards: 2,
      redCards: 0,
      playerOfTheMatch: 6,
      passAccuracy: 88.5,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 8.8, goals: 1, assists: 2, minutes: 90 },
      { opponent: 'Plateau United Feeders', date: '2026-03-08', result: 'W', score: '2 - 0', rating: 8.2, goals: 1, assists: 0, minutes: 85 },
      { opponent: 'Riyom United', date: '2026-02-28', result: 'D', score: '1 - 1', rating: 7.5, goals: 0, assists: 1, minutes: 90 },
      { opponent: 'Bukuru Lions FC', date: '2026-02-20', result: 'W', score: '4 - 2', rating: 9.0, goals: 2, assists: 1, minutes: 90 },
    ],
    quote: 'Discipline in training translates to magic on match day.',
    socialHandle: '@emmanuel_d10',
  },
  {
    id: 'victor-nwosu',
    name: 'Victor Nwosu',
    nickname: 'The Bullet',
    jerseyNumber: 9,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Forward',
    detailedPosition: 'Center Forward / Striker',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    age: 20,
    dateOfBirth: '2006-08-19',
    height: "6' 2\" (188 cm)",
    weight: '80 kg',
    preferredFoot: 'Both',
    nationality: 'Nigeria',
    stateOfOrigin: 'Imo / Plateau',
    joinedYear: 2022,
    marketValueEstimate: '€220,000',
    bio: 'A clinical, powerhouse striker known for his blistering acceleration and aerial supremacy. Victor topped the scoring charts with 18 goals in all competitions in 2024.',
    scoutReport: 'Explosive burst in behind defensive lines, lethal both-footed finishing, dominates aerial duels with 74% win rate.',
    achievements: [
      'BKFA Golden Boot Winner 2024 (18 Goals)',
      'Hat-trick in State Cup Quarter-finals',
    ],
    attributes: {
      pace: 92,
      shooting: 89,
      passing: 70,
      dribbling: 81,
      defending: 40,
      physical: 87,
    },
    seasonStats: {
      appearances: 20,
      goals: 18,
      assists: 4,
      minutesPlayed: 1720,
      yellowCards: 3,
      redCards: 0,
      playerOfTheMatch: 5,
      passAccuracy: 76.0,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 8.5, goals: 2, assists: 0, minutes: 82 },
      { opponent: 'Plateau United Feeders', date: '2026-03-08', result: 'W', score: '2 - 0', rating: 7.9, goals: 1, assists: 0, minutes: 90 },
      { opponent: 'Riyom United', date: '2026-02-28', result: 'D', score: '1 - 1', rating: 7.0, goals: 1, assists: 0, minutes: 90 },
    ],
    quote: 'Every ball in the box is an opportunity to score.',
  },
  {
    id: 'sadiq-abdullahi',
    name: 'Sadiq Abdullahi',
    nickname: 'The Rock',
    jerseyNumber: 4,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Defender',
    detailedPosition: 'Central Defender',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    viceCaptain: true,
    age: 22,
    dateOfBirth: '2004-01-25',
    height: "6' 3\" (191 cm)",
    weight: '84 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2020,
    marketValueEstimate: '€160,000',
    bio: 'Commanding center-back with incredible tackling precision and defensive organization. Sadiq is the bedrock of the BKFA backline.',
    scoutReport: 'Imposing presence, timing in standing tackles is near flawless, highly vocal leader organizing the defensive structure.',
    achievements: [
      'BKFA Defender of the Year 2024',
      '11 Clean Sheets in 2024 Season',
    ],
    attributes: {
      pace: 78,
      shooting: 52,
      passing: 75,
      dribbling: 66,
      defending: 90,
      physical: 89,
    },
    seasonStats: {
      appearances: 23,
      goals: 3,
      assists: 1,
      cleanSheets: 11,
      minutesPlayed: 2070,
      yellowCards: 4,
      redCards: 0,
      playerOfTheMatch: 3,
      passAccuracy: 84.0,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 7.8, goals: 0, assists: 0, minutes: 90 },
      { opponent: 'Plateau United Feeders', date: '2026-03-08', result: 'W', score: '2 - 0', rating: 8.6, goals: 0, assists: 0, minutes: 90 },
    ],
    quote: 'Defense is our shield; clean sheets win championships.',
  },
  {
    id: 'godwin-bature',
    name: 'Godwin Bature',
    nickname: 'Spider-Hands',
    jerseyNumber: 1,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Goalkeeper',
    detailedPosition: 'Goalkeeper',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    age: 21,
    dateOfBirth: '2005-02-14',
    height: "6' 4\" (193 cm)",
    weight: '82 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2021,
    marketValueEstimate: '€140,000',
    bio: 'Agile shot stopper known for miraculous penalty saves and pinpoint distribution kickouts to instigate fast counter-attacks.',
    scoutReport: 'Exceptional reflex speed, strong commanding box presence during corners, 4 penalty saves recorded in 2024.',
    achievements: [
      'Golden Glove Plateau Grassroots Cup 2024',
      'Award of Excellence - Best Goalkeeper BKFA Night 2024',
    ],
    attributes: {
      pace: 68,
      shooting: 30,
      passing: 78,
      dribbling: 55,
      defending: 88,
      physical: 85,
    },
    seasonStats: {
      appearances: 21,
      goals: 0,
      assists: 1,
      cleanSheets: 10,
      minutesPlayed: 1890,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 3,
      passAccuracy: 81.0,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 7.9, goals: 0, assists: 0, minutes: 90 },
      { opponent: 'Plateau United Feeders', date: '2026-03-08', result: 'W', score: '2 - 0', rating: 8.8, goals: 0, assists: 0, minutes: 90 },
    ],
  },
  {
    id: 'samuel-chuwang',
    name: 'Samuel Chuwang',
    nickname: 'Flash',
    jerseyNumber: 7,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Forward',
    detailedPosition: 'Right Winger',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    age: 19,
    dateOfBirth: '2007-06-11',
    height: "5' 9\" (175 cm)",
    weight: '68 kg',
    preferredFoot: 'Left',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€195,000',
    bio: 'Electric left-footed inverted winger capable of tearing through defenses with dazzling footwork and ferocious cut-inside shots.',
    scoutReport: 'Top speed of 34.8 km/h, elite 1v1 dribbling success rate (78%), dangerous direct free-kick specialist.',
    achievements: ['Breakthrough Young Player 2024', '11 Goals & 8 Assists in 2024'],
    attributes: {
      pace: 94,
      shooting: 84,
      passing: 79,
      dribbling: 91,
      defending: 45,
      physical: 72,
    },
    seasonStats: {
      appearances: 19,
      goals: 11,
      assists: 8,
      minutesPlayed: 1540,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 4,
      passAccuracy: 82.0,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 8.3, goals: 0, assists: 1, minutes: 78 },
      { opponent: 'Plateau United Feeders', date: '2026-03-08', result: 'W', score: '2 - 0', rating: 7.7, goals: 0, assists: 0, minutes: 90 },
    ],
  },
  {
    id: 'kalu-okonkwo',
    name: 'Kalu Okonkwo',
    nickname: 'The Engine',
    jerseyNumber: 6,
    category: 'mens-first',
    categoryName: "Men's First Team",
    gender: 'Male',
    position: 'Midfielder',
    detailedPosition: 'Defensive Midfielder (CDM)',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
    age: 21,
    dateOfBirth: '2005-09-03',
    height: "6' 0\" (183 cm)",
    weight: '76 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Abia / Plateau',
    joinedYear: 2022,
    marketValueEstimate: '€170,000',
    bio: 'Tireless ball recovery machine who protects the back four with relentless pressing, game-reading interceptions, and crisp progressive passing.',
    scoutReport: 'Averages 11.2 km distance per game, top interception numbers in the regional league (4.1 per game).',
    achievements: ['Most Recoveries Award BKFA 2024', 'Unsung Hero Award'],
    attributes: {
      pace: 79,
      shooting: 68,
      passing: 83,
      dribbling: 76,
      defending: 87,
      physical: 88,
    },
    seasonStats: {
      appearances: 22,
      goals: 2,
      assists: 5,
      minutesPlayed: 1910,
      yellowCards: 5,
      redCards: 0,
      playerOfTheMatch: 2,
      passAccuracy: 89.2,
    },
    recentMatches: [
      { opponent: 'Jos City Stars', date: '2026-03-14', result: 'W', score: '3 - 1', rating: 8.0, goals: 0, assists: 0, minutes: 90 },
    ],
  },

  // ===================== WOMEN'S FIRST TEAM (QUEENS) =====================
  {
    id: 'blessing-pam',
    name: 'Blessing Pam',
    nickname: 'Queen of Jos',
    jerseyNumber: 10,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Midfielder',
    detailedPosition: 'Attacking Midfielder / Playmaker',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    captain: true,
    age: 21,
    dateOfBirth: '2005-03-22',
    height: "5' 8\" (173 cm)",
    weight: '62 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2021,
    marketValueEstimate: '€150,000',
    bio: 'Inspirational captain of the BKFA Queens. Blessing combines majestic ball mastery, silky turns, and incredible leadership that inspires the women’s squad to national prominence.',
    scoutReport: 'High football IQ, brilliant dribbling in tight channels, excellent dead-ball accuracy with 5 direct free-kick goals in 2024.',
    achievements: [
      'BKFA Female Player of the Year 2024',
      'Jos Women Grassroots Cup MVP 2024',
      '15 Goals & 12 Assists in 2024 Season',
    ],
    attributes: {
      pace: 86,
      shooting: 85,
      passing: 89,
      dribbling: 90,
      defending: 60,
      physical: 75,
    },
    seasonStats: {
      appearances: 18,
      goals: 15,
      assists: 12,
      minutesPlayed: 1590,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 7,
      passAccuracy: 87.0,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 9.2, goals: 2, assists: 1, minutes: 90 },
      { opponent: 'Nasarawa Amazons Feeders', date: '2026-03-05', result: 'W', score: '2 - 1', rating: 8.4, goals: 1, assists: 1, minutes: 90 },
      { opponent: 'Jos Angels', date: '2026-02-24', result: 'W', score: '4 - 0', rating: 8.9, goals: 1, assists: 2, minutes: 84 },
    ],
    quote: 'We play with our heart for the crest and our community.',
    socialHandle: '@blessing_pam10',
  },
  {
    id: 'mercy-adebayo',
    name: 'Mercy Adebayo',
    nickname: 'The Spear',
    jerseyNumber: 9,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Forward',
    detailedPosition: 'Striker / Center Forward',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    age: 20,
    dateOfBirth: '2006-05-18',
    height: "5' 9\" (176 cm)",
    weight: '64 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Oyo / Plateau',
    joinedYear: 2022,
    marketValueEstimate: '€165,000',
    bio: 'Fearsome finisher with devastating pace and clinical composure in 1v1 situations against goalkeepers. Winner of the 2024 Women’s Grassroots Golden Boot.',
    scoutReport: 'Deadly finishing conversion rate (31%), instinctive movement across defenders’ blind sides.',
    achievements: ['Golden Boot Winner 2024 (21 Goals in all competitions)', 'BKFA Goal of the Season 2024'],
    attributes: {
      pace: 93,
      shooting: 90,
      passing: 73,
      dribbling: 83,
      defending: 38,
      physical: 80,
    },
    seasonStats: {
      appearances: 18,
      goals: 21,
      assists: 5,
      minutesPlayed: 1530,
      yellowCards: 2,
      redCards: 0,
      playerOfTheMatch: 6,
      passAccuracy: 78.0,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 8.7, goals: 1, assists: 0, minutes: 90 },
      { opponent: 'Nasarawa Amazons Feeders', date: '2026-03-05', result: 'W', score: '2 - 1', rating: 8.0, goals: 1, assists: 0, minutes: 90 },
    ],
  },
  {
    id: 'faith-dungyur',
    name: 'Faith Dungyur',
    nickname: 'Iron Lady',
    jerseyNumber: 5,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Defender',
    detailedPosition: 'Center Back',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    viceCaptain: true,
    age: 22,
    dateOfBirth: '2004-11-09',
    height: "5' 10\" (178 cm)",
    weight: '68 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2021,
    marketValueEstimate: '€120,000',
    bio: 'Rock-solid defender who commands the defensive line with supreme discipline and physical prowess.',
    scoutReport: 'Dominates aerial aerials, tactical intelligence, calmness under counter-press.',
    achievements: ['Best Female Defender BKFA Award Night 2024', '12 Clean Sheets'],
    attributes: {
      pace: 80,
      shooting: 48,
      passing: 78,
      dribbling: 70,
      defending: 89,
      physical: 86,
    },
    seasonStats: {
      appearances: 18,
      goals: 2,
      assists: 1,
      cleanSheets: 12,
      minutesPlayed: 1620,
      yellowCards: 2,
      redCards: 0,
      playerOfTheMatch: 3,
      passAccuracy: 85.4,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 8.5, goals: 0, assists: 0, minutes: 90 },
    ],
  },
  {
    id: 'hannah-gyang',
    name: 'Hannah Gyang',
    nickname: 'The Wall',
    jerseyNumber: 1,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Goalkeeper',
    detailedPosition: 'Goalkeeper',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    age: 20,
    dateOfBirth: '2006-02-02',
    height: "5' 11\" (180 cm)",
    weight: '69 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2022,
    marketValueEstimate: '€110,000',
    bio: 'A fearless goalkeeper with acrobatic reflex saves and high command of aerial delivery in the penalty area.',
    scoutReport: 'Great reaction saves in 1-on-1 situations, strong verbal communication to organize the defensive block.',
    achievements: ['Golden Gloves BKFA Queens 2024', '12 Clean Sheets'],
    attributes: {
      pace: 70,
      shooting: 25,
      passing: 76,
      dribbling: 58,
      defending: 87,
      physical: 83,
    },
    seasonStats: {
      appearances: 18,
      goals: 0,
      assists: 0,
      cleanSheets: 12,
      minutesPlayed: 1620,
      yellowCards: 0,
      redCards: 0,
      playerOfTheMatch: 2,
      passAccuracy: 80.0,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 8.6, goals: 0, assists: 0, minutes: 90 },
    ],
  },
  {
    id: 'chidinma-uche',
    name: 'Chidinma Uche',
    nickname: 'Cheetah',
    jerseyNumber: 11,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Forward',
    detailedPosition: 'Left Winger',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    age: 19,
    dateOfBirth: '2007-09-14',
    height: "5' 7\" (170 cm)",
    weight: '59 kg',
    preferredFoot: 'Left',
    nationality: 'Nigeria',
    stateOfOrigin: 'Enugu / Plateau',
    joinedYear: 2023,
    marketValueEstimate: '€135,000',
    bio: 'Explosive winger with electrifying acceleration and crossing mastery who creates constant danger on the flanks.',
    scoutReport: 'High dribble volume, accurate low-driven crosses, exceptional work rate tracking back.',
    achievements: ['Most Improved Player 2024', '9 Goals, 10 Assists in 2024'],
    attributes: {
      pace: 92,
      shooting: 81,
      passing: 84,
      dribbling: 88,
      defending: 48,
      physical: 70,
    },
    seasonStats: {
      appearances: 17,
      goals: 9,
      assists: 10,
      minutesPlayed: 1390,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 3,
      passAccuracy: 83.5,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 8.1, goals: 0, assists: 2, minutes: 75 },
    ],
  },
  {
    id: 'joy-yakubu',
    name: 'Joy Yakubu',
    nickname: 'The Architect',
    jerseyNumber: 8,
    category: 'womens-first',
    categoryName: "Women's First Team (Queens)",
    gender: 'Female',
    position: 'Midfielder',
    detailedPosition: 'Central Midfielder (Box-to-Box)',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    age: 20,
    dateOfBirth: '2006-07-28',
    height: "5' 8\" (173 cm)",
    weight: '63 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2022,
    marketValueEstimate: '€125,000',
    bio: 'Box-to-box engine who links defense and attack seamlessly with energetic pressing and dynamic late runs into the penalty box.',
    scoutReport: 'Covers massive ground, high tackle success rate (82%), powerful long range strike.',
    achievements: ['Midfield Dynamo Award 2024', '6 Goals from Midfield'],
    attributes: {
      pace: 82,
      shooting: 78,
      passing: 85,
      dribbling: 80,
      defending: 82,
      physical: 84,
    },
    seasonStats: {
      appearances: 18,
      goals: 6,
      assists: 8,
      minutesPlayed: 1510,
      yellowCards: 3,
      redCards: 0,
      playerOfTheMatch: 2,
      passAccuracy: 86.0,
    },
    recentMatches: [
      { opponent: 'Plateau Queens FC', date: '2026-03-12', result: 'W', score: '3 - 0', rating: 8.3, goals: 0, assists: 0, minutes: 90 },
    ],
  },

  // ===================== BOYS YOUTH ACADEMY (U17/U19) =====================
  {
    id: 'david-kangyang',
    name: 'David Kangyang',
    nickname: 'Wonderkid',
    jerseyNumber: 17,
    category: 'boys-academy',
    categoryName: 'Boys Youth Academy (U19)',
    gender: 'Male',
    position: 'Forward',
    detailedPosition: 'Left / Right Inverted Forward',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    captain: true,
    age: 17,
    dateOfBirth: '2009-01-15',
    height: "5' 10\" (178 cm)",
    weight: '67 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€95,000',
    bio: 'Sensational teenage prodigy who scored 24 goals for the U17 and U19 squads in 2024. Scouted by national youth teams for his astonishing dribbling flair.',
    scoutReport: 'Phenomenal close control, creative flair, fearless against senior defenders in training scrimmages.',
    achievements: ['BKFA Academy Player of the Year 2024', 'Jos Youth Cup Top Scorer (14 goals)'],
    attributes: {
      pace: 91,
      shooting: 86,
      passing: 80,
      dribbling: 92,
      defending: 42,
      physical: 74,
    },
    seasonStats: {
      appearances: 16,
      goals: 24,
      assists: 9,
      minutesPlayed: 1380,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 8,
      passAccuracy: 84.0,
    },
    recentMatches: [
      { opponent: 'Bukuru Youth Stars', date: '2026-03-11', result: 'W', score: '5 - 1', rating: 9.6, goals: 3, assists: 1, minutes: 80 },
    ],
    quote: 'Dream big, work tirelessly every day.',
  },
  {
    id: 'joshua-dalyop',
    name: 'Joshua Dalyop',
    nickname: 'General',
    jerseyNumber: 3,
    category: 'boys-academy',
    categoryName: 'Boys Youth Academy (U19)',
    gender: 'Male',
    position: 'Defender',
    detailedPosition: 'Left Back / Wing Back',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    age: 18,
    dateOfBirth: '2008-05-30',
    height: "5' 11\" (180 cm)",
    weight: '70 kg',
    preferredFoot: 'Left',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€70,000',
    bio: 'Modern attacking fullback with explosive overlapping runs and pinpoint crossing delivery.',
    scoutReport: 'High stamina, exceptional crossing accuracy, solid 1v1 defensive containment.',
    achievements: ['Academy Best Fullback 2024'],
    attributes: {
      pace: 88,
      shooting: 65,
      passing: 82,
      dribbling: 80,
      defending: 81,
      physical: 78,
    },
    seasonStats: {
      appearances: 15,
      goals: 3,
      assists: 7,
      minutesPlayed: 1290,
      yellowCards: 2,
      redCards: 0,
      playerOfTheMatch: 2,
      passAccuracy: 83.0,
    },
    recentMatches: [
      { opponent: 'Bukuru Youth Stars', date: '2026-03-11', result: 'W', score: '5 - 1', rating: 8.2, goals: 0, assists: 2, minutes: 90 },
    ],
  },
  {
    id: 'musa-haruna',
    name: 'Musa Haruna',
    nickname: 'The Sentinel',
    jerseyNumber: 1,
    category: 'boys-academy',
    categoryName: 'Boys Youth Academy (U19)',
    gender: 'Male',
    position: 'Goalkeeper',
    detailedPosition: 'Goalkeeper',
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
    age: 17,
    dateOfBirth: '2009-08-04',
    height: "6' 2\" (188 cm)",
    weight: '75 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€65,000',
    bio: 'Tall, agile youth goalkeeper with commanding presence in the air and lightning quick reflexes on low shots.',
    scoutReport: 'Great wingspan, calm under high balls, rapid distribution.',
    achievements: ['Best Youth Goalkeeper BKFA 2024'],
    attributes: {
      pace: 65,
      shooting: 22,
      passing: 74,
      dribbling: 50,
      defending: 84,
      physical: 81,
    },
    seasonStats: {
      appearances: 15,
      goals: 0,
      assists: 0,
      cleanSheets: 8,
      minutesPlayed: 1350,
      yellowCards: 0,
      redCards: 0,
      playerOfTheMatch: 2,
      passAccuracy: 79.0,
    },
    recentMatches: [
      { opponent: 'Bukuru Youth Stars', date: '2026-03-11', result: 'W', score: '5 - 1', rating: 8.0, goals: 0, assists: 0, minutes: 90 },
    ],
  },

  // ===================== GIRLS YOUTH ACADEMY (U17/U19) =====================
  {
    id: 'grace-bot',
    name: 'Grace Bot',
    nickname: 'Jewel of Plateau',
    jerseyNumber: 10,
    category: 'girls-academy',
    categoryName: 'Girls Youth Academy (U19)',
    gender: 'Female',
    position: 'Midfielder',
    detailedPosition: 'Central Midfielder / Playmaker',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    captain: true,
    age: 17,
    dateOfBirth: '2009-03-10',
    height: "5' 7\" (170 cm)",
    weight: '58 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€80,000',
    bio: 'Exciting midfield talent known for incredible technical poise, dribbling agility, and commanding game control in youth matches.',
    scoutReport: 'Silky ball control, natural vision, excellent discipline and training commitment.',
    achievements: ['Girls Academy MVP 2024', 'Jos Inter-School Champion 2024'],
    attributes: {
      pace: 85,
      shooting: 79,
      passing: 88,
      dribbling: 89,
      defending: 62,
      physical: 72,
    },
    seasonStats: {
      appearances: 14,
      goals: 12,
      assists: 11,
      minutesPlayed: 1180,
      yellowCards: 0,
      redCards: 0,
      playerOfTheMatch: 5,
      passAccuracy: 88.0,
    },
    recentMatches: [
      { opponent: 'Riyom Girls Academy', date: '2026-03-10', result: 'W', score: '4 - 0', rating: 9.3, goals: 2, assists: 2, minutes: 80 },
    ],
    quote: 'Hard work beats talent when talent fails to work hard.',
  },
  {
    id: 'esther-jatau',
    name: 'Esther Jatau',
    nickname: 'Rocket',
    jerseyNumber: 7,
    category: 'girls-academy',
    categoryName: 'Girls Youth Academy (U19)',
    gender: 'Female',
    position: 'Forward',
    detailedPosition: 'Right Winger / Striker',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    age: 16,
    dateOfBirth: '2010-06-25',
    height: "5' 6\" (168 cm)",
    weight: '55 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2024,
    marketValueEstimate: '€75,000',
    bio: 'Blistering young forward with raw pace and an eye for spectacular long-range finishes.',
    scoutReport: 'Lightning acceleration, relentless pressing on opposition defenders, natural goal poacher.',
    achievements: ['Rising Star Award BKFA Night 2024', '14 Goals in 12 Academy Matches'],
    attributes: {
      pace: 93,
      shooting: 83,
      passing: 74,
      dribbling: 86,
      defending: 40,
      physical: 68,
    },
    seasonStats: {
      appearances: 12,
      goals: 14,
      assists: 6,
      minutesPlayed: 980,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 4,
      passAccuracy: 79.5,
    },
    recentMatches: [
      { opponent: 'Riyom Girls Academy', date: '2026-03-10', result: 'W', score: '4 - 0', rating: 8.9, goals: 2, assists: 0, minutes: 75 },
    ],
  },
  {
    id: 'patience-pwayidi',
    name: 'Patience Pwayidi',
    nickname: 'Shield',
    jerseyNumber: 4,
    category: 'girls-academy',
    categoryName: 'Girls Youth Academy (U19)',
    gender: 'Female',
    position: 'Defender',
    detailedPosition: 'Center Back',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    viceCaptain: true,
    age: 18,
    dateOfBirth: '2008-02-17',
    height: "5' 9\" (175 cm)",
    weight: '62 kg',
    preferredFoot: 'Right',
    nationality: 'Nigeria',
    stateOfOrigin: 'Plateau State',
    joinedYear: 2023,
    marketValueEstimate: '€60,000',
    bio: 'Disciplined and athletic defender who excels at defensive duels and leadership on the pitch.',
    scoutReport: 'Solid recovery speed, great timing in slide tackles, dependable aerial presence.',
    achievements: ['Most Disciplined Player 2024'],
    attributes: {
      pace: 81,
      shooting: 45,
      passing: 76,
      dribbling: 68,
      defending: 85,
      physical: 80,
    },
    seasonStats: {
      appearances: 14,
      goals: 1,
      assists: 1,
      cleanSheets: 8,
      minutesPlayed: 1140,
      yellowCards: 1,
      redCards: 0,
      playerOfTheMatch: 1,
      passAccuracy: 82.0,
    },
    recentMatches: [
      { opponent: 'Riyom Girls Academy', date: '2026-03-10', result: 'W', score: '4 - 0', rating: 8.4, goals: 0, assists: 0, minutes: 80 },
    ],
  },
];

export const FIXTURES_DATA: MatchFixture[] = [
  {
    id: 'fix-01',
    competition: 'Plateau State Grassroots Championship',
    homeTeam: { name: 'Blessed KAA FA', isBKFA: true },
    awayTeam: { name: 'Mighty Jets Feeders', isBKFA: false },
    category: 'mens-first',
    date: '2026-04-04',
    time: '15:30 GMT+1',
    venue: 'Science Day School Arena, Cele Bridge, Jos',
    status: 'UPCOMING',
  },
  {
    id: 'fix-02',
    competition: 'Plateau Women League Cup',
    homeTeam: { name: 'Blessed KAA Queens', isBKFA: true },
    awayTeam: { name: 'Tin City Angels', isBKFA: false },
    category: 'womens-first',
    date: '2026-04-06',
    time: '14:00 GMT+1',
    venue: 'Rwang Pam Stadium, Jos',
    status: 'UPCOMING',
  },
  {
    id: 'fix-03',
    competition: 'Jos Youth Elite Super Cup',
    homeTeam: { name: 'Bukuru All Stars U19', isBKFA: false },
    awayTeam: { name: 'Blessed KAA Academy Boys', isBKFA: true },
    category: 'boys-academy',
    date: '2026-04-10',
    time: '10:00 GMT+1',
    venue: 'Science Day School Pitch, Jos',
    status: 'UPCOMING',
  },
  {
    id: 'fix-04',
    competition: 'Relentless Foundation Grassroots Cup',
    homeTeam: { name: 'Blessed KAA FA', isBKFA: true },
    awayTeam: { name: 'Jos City Stars', isBKFA: false },
    category: 'mens-first',
    date: '2026-03-14',
    time: '16:00 GMT+1',
    venue: 'Science Day Arena, Jos',
    status: 'COMPLETED',
    score: { home: 3, away: 1 },
    highlights: 'Emmanuel Danjuma 24\', Victor Nwosu 58\', 81\' (BKFA) | Adams 67\' (JCS)',
  },
  {
    id: 'fix-05',
    competition: 'Plateau Women Invitational',
    homeTeam: { name: 'Plateau Queens FC', isBKFA: false },
    awayTeam: { name: 'Blessed KAA Queens', isBKFA: true },
    category: 'womens-first',
    date: '2026-03-12',
    time: '15:00 GMT+1',
    venue: 'Rwang Pam Stadium, Jos',
    status: 'COMPLETED',
    score: { home: 0, away: 3 },
    highlights: 'Blessing Pam 18\', 74\', Mercy Adebayo 42\' (BKFA)',
  },
];

export const CLUB_AWARDS: ClubAward[] = [
  {
    year: 2024,
    title: 'BKFA Annual Award of Excellence Night',
    recipient: 'Grassroots Coaches & Academy Stars',
    category: 'Club & Community Event',
    description: 'Held at Science Day School Hall, Cele Bridge, Jos. Celebrating leadership, top goalscorers, best academy students, and sports development contributors across Plateau State.',
  },
  {
    year: 2024,
    title: 'Plateau Grassroots League Champions',
    recipient: 'BKFA Men’s First Team',
    category: 'Championship Trophy',
    description: 'Unbeaten run in 14 matches to claim the prestigious Plateau Grassroots trophy in Jos.',
  },
  {
    year: 2024,
    title: 'Women Invitational Cup Gold Medal',
    recipient: 'BKFA Queens',
    category: 'Championship Trophy',
    description: 'Conceded only 2 goals in 6 matches on their way to lifting the women tournament cup.',
  },
];
